import streamlit as st
import requests
import pandas as pd
import re

# ============================================================
# CONFIG
# ============================================================
st.set_page_config(
    page_title="NSE Order Intelligence",
    layout="wide",
    page_icon="📦"
)

st.title("📦 NSE Big Order Intelligence (Cloud Safe)")

SYMBOLS = ['20MICRONS','21STCENMGM','360ONE','3IINFOLTD','3MINDIA','3PLAND','5PAISA','63MOONS','A2ZINFRA','AAATECH','AADHARHFC','AAKASH','AAREYDRUGS','AARON','AARTECH','AARTIDRUGS','AARTIIND',
'AARTIPHARM','AARTISURF','AARVEEDEN','AARVI','AAVAS','ABAN','ABB','ABBOTINDIA','ABCAPITAL','ABDL','ABFRL','ABGSEC','ABINFRA','ABLBL','ABMINTLLTD','ABREL','ABSLAMC','ABSLBANETF',
'ABSLLIQUID','ABSLNN50ET','ABSLPSE','ACC','ACCELYA','ACCURACY','ACE','ACEINTEG','ACI','ACL','ACLGATI','ACMESOLAR','ACUTAAS','ADANIENSOL','ADANIENT','ADANIGREEN','ADANIPORTS',
'ADANIPOWER','ADFFOODS','ADL','ADOR','ADROITINFO','ADSL','ADVANIHOTR','ADVENZYMES','AEGISLOG','AEGISVOPAK','AEROENTER','AEROFLEX','AERONEU','AETHER','AFCONS','AFFLE','AFFORDABLE',
'AFIL','AFSL','AGARIND','AGARWALEYE','AGI','AGIIL','AGRITECH','AGROPHOS','AGSTRA','AHLADA','AHLEAST','AHLUCONT','AIAENG','AIIL','AIRAN','AIROLAM','AJANTPHARM','AJAXENGG','AJMERA',
'AJOONI','AKASH','AKG','AKI','AKSHAR','AKSHARCHEM','AKSHOPTFBR','AKUMS','AKZOINDIA','ALANKIT','ALBERTDAVD','ALEMBICLTD','ALICON','ALIVUS','ALKALI','ALKEM','ALKYLAMINE','ALLCARGO',
'ALLDIGI','ALLTIME','ALMONDZ','ALOKINDS','ALPA','ALPHA','ALPHAETF','ALPHAGEO','ALPL30IETF','ALPSINDUS','AMBER','AMBICAAGAR','AMBIKCO','AMBUJACEM','AMDIND','AMJLAND','AMNPLST',
'AMRUTANJAN','ANANDRATHI','ANANTRAJ','ANDHRAPAP','ANDHRSUGAR','ANGELONE','ANIKINDS','ANMOL','ANTGRAPHIC','ANTHEM','ANUHPHR','ANUP','ANURAS','AONELIQUID','AONENIFTY','AONETOTAL',
'APARINDS','APCL','APCOTEXIND','APEX','APLAPOLLO','APLLTD','APOLLO','APOLLOHOSP','APOLLOPIPE','APOLLOTYRE','APOLSINHOT','APTECHT','APTUS','ARCHIDPLY','ARCHIES','ARE&M','ARENTERP',
'ARFIN','ARIES','ARIHANTCAP','ARIHANTSUP','ARISINFRA','ARKADE','ARMANFIN','AROGRANITE','ARROWGREEN','ARSSINFRA','ARTEMISMED','ARTNIRMAN','ARVEE','ARVIND','ARVINDFASN','ARVSMART',
'ASAHIINDIA','ASAHISONG','ASAL','ASALCBR','ASHAPURMIN','ASHIANA','ASHIMASYN','ASHOKA','ASHOKAMET','ASHOKLEY','ASIANENE','ASIANHOTNR','ASIANPAINT','ASIANTILES','ASKAUTOLTD','ASMS',
'ASPINWALL','ASTEC','ASTERDM','ASTRAL','ASTRAMICRO','ASTRAZEN','ASTRON','ATALREAL','ATAM','ATGL','ATHERENERG','ATL','ATLANTAA','ATLASCYCLE','ATUL','ATULAUTO','AUBANK','AURIONPRO',
'AUROPHARMA','AURUM','AUSOMENT','AUTOAXLES','AUTOBEES','AUTOIETF','AUTOIND','AVADHSUGAR','AVALON','AVANTEL','AVANTIFEED','AVG','AVL','AVONMORE','AVROIND','AVTNPL','AWFIS','AWHCL',
'AWL','AXISBANK','AXISBNKETF','AXISBPSETF','AXISCADES','AXISCETF','AXISGOLD','AXISHCETF','AXISILVER','AXISNIFTY','AXISTECETF','AXISVALUE','AXITA','AXSENSEX','AYMSYNTEX','AZAD',
'BAFNAPH','BAGFILMS','BAIDFIN','BAJAJ_AUTO','BAJAJCON','BAJAJELEC','BAJAJFINSV','BAJAJHCARE','BAJAJHFL','BAJAJHIND','BAJAJHLDNG','BAJAJINDEF','BAJEL','BAJFINANCE','BALAJEE',
'BALAJITELE','BALAMINES','BALAXI','BALKRISHNA','BALKRISIND','BALMLAWRIE','BALPHARMA','BALRAMCHIN','BALUFORGE','BANARBEADS','BANARISUG','BANCOINDIA','BANDHANBNK','BANG','BANKA',
'BANKBARODA','BANKBEES','BANKBETF','BANKETF','BANKETFADD','BANKIETF','BANKINDIA','BANKNIFTY1','BANKPSU','BANSALWIRE','BANSWRAS','BARBEQUE','BASF','BASML','BATAINDIA','BAYERCROP',
'BBETF0432','BBL','BBNPNBETF','BBNPPGOLD','BBOX','BBTC','BBTCL','BCG','BCLIND','BCONCEPTS','BDL','BEARDSELL','BECTORFOOD','BEDMUTHA','BEL','BELLACASA','BELRISE','BEML','BEPL',
'BERGEPAINT','BESTAGRO','BFINVEST','BFSI','BFUTILITIE','BGRENERGY','BHAGCHEM','BHAGERIA','BHAGYANGR','BHANDARI','BHARATFORG','BHARATGEAR','BHARATRAS','BHARATSE','BHARATWIRE',
'BHARTIARTL','BHARTIHEXA','BHEL','BIGBLOC','BIKAJI','BIL','BILVYAPAR','BIOCON','BIOFILCHEM','BIRLACABLE','BIRLACORPN','BIRLAMONEY','BIRLANU','BLACKBUCK','BLAL','BLBLIMITED',
'BLISSGVS','BLKASHYAP','BLS','BLSE','BLUECOAST','BLUEDART','BLUEJET','BLUESTARCO','BLUESTONE','BLUSPRING','BODALCHEM','BOHRAIND','BOMDYEING','BORANA','BOROLTD','BORORENEW',
'BOROSCI','BOSCHLTD','BPCL','BPL','BRIGADE','BRIGHOTEL','BRITANNIA','BRNL','BROOKS','BSE','BSE500IETF','BSHSL','BSL','BSLGOLDETF','BSLNIFTY','BSLSENETFG','BSOFT','BTML','BUTTERFLY',
'BVCL','BYKE','CALSOFT','CAMLINFINE','CAMPUS','CAMS','CANBK','CANFINHOME','CANTABIL','CAPACITE','CAPITALSFB','CAPLIPOINT','CAPTRUST','CARBORUNIV','CARERATING','CARRARO','CARTRADE',
'CARYSIL','CASHIETF','CASTROLIND','CCCL','CCHHL','CCL','CDSL','CEATLTD','CEIGALL','CELEBRITY','CELLO','CENTENKA','CENTEXT','CENTRALBK','CENTRUM','CENTUM','CENTURYPLY','CERA','CESC',
'CEWATER','CGCL','CGPOWER','CHALET','CHAMBLFERT','CHEMBOND','CHEMBONDCH','CHEMCON','CHEMFAB','CHEMPLASTS','CHENNPETRO','CHEVIOT','CHOICEIN','CHOLAFIN','CHOLAHLDNG','CIEINDIA','CIFL',
'CIGNITITEC','CINELINE','CINEVISTA','CIPLA','CLEAN','CLEDUCATE','CLSEL','CMSINFO','COALINDIA','COASTCORP','COCHINSHIP','COFFEEDAY','COFORGE','COHANCE','COLPAL','COMMOIETF','COMPUSOFT',
'COMSYN','CONCOR','CONCORDBIO','CONFIPET','CONS','CONSOFINVT','CONSUMBEES','CONSUMER','CONSUMIETF','CONTROLPR','CORALFINAC','CORDSCABLE','COROMANDEL','COSMOFIRST','COUNCODOS','CPCAP',
'CPPLUS','CPSEETF','CRAFTSMAN','CREATIVE','CREATIVEYE','CREDITACC','CREST','CRISIL','CRIZAC','CROMPTON','CROWN','CSBBANK','CSLFINANCE','CTE','CUB','CUBEXTUB','CUMMINSIND','CUPID',
'CURAA','CYBERMEDIA','CYBERTECH','CYIENT','CYIENTDLM','DABUR','DALBHARAT','DALMIASUG','DAMCAPITAL','DAMODARIND','DANGEE','DATAMATICS','DATAPATTNS','DAVANGERE','DBCORP','DBEIL','DBL',
'DBOL','DBREALTY','DBSTOCKBRO','DCAL','DCBBANK','DCI','DCM','DCMFINSERV','DCMNVL','DCMSHRIRAM','DCMSRIND','DCW','DCXINDIA','DDEVPLSTIK','DECCANCE','DEEDEV','DEEPAKFERT','DEEPAKNTR',
'DEEPINDS','DELHIVERY','DELPHIFX','DELTACORP','DELTAMAGNT','DEN','DENORA','DENTA','DEVIT','DEVYANI','DGCONTENT','DHAMPURSUG','DHANBANK','DHANI','DHANUKA','DHARAN','DHARMAJ','DHRUV',
'DHUNINV','DIACABS','DIAMINESQ','DIAMONDYD','DICIND','DIFFNKG','DIGIDRIVE','DIGISPICE','DIGITIDE','DIGJAMLMTD','DIL','DISHTV','DIVGIITTS','DIVISLAB','DIVOPPBEES','DIXON','DJML','DLF',
'DLINKINDIA','DMART','DMCC','DNAMEDIA','DODLA','DOLATALGO','DOLLAR','DOLPHIN','DOMS','DONEAR','DPABHUSHAN','DPSCLTD','DPWIRES','DRCSYSTEMS','DREAMFOLKS','DREDGECORP','DRREDDY',
'DSSL','DTIL','DUCON','DVL','DWARKESH','DYCL','DYNAMATECH','DYNPRO','E2E','EASEMYTRIP','EBANKNIFTY','EBBETF0430','EBBETF0431','EBBETF0433','EBGNG','ECAPINSURE','ECLERX','ECOSMOBLTY',
'EDELWEISS','EFCIL','EGOLD','EICHERMOT','EIDPARRY','EIEL','EIFFL','EIHAHOTELS','EIHOTEL','EIMCOELECO','EKC','ELDEHSG','ELECON','ELECTCAST','ELECTHERM','ELGIEQUIP','ELGIRUBCO','ELIN',
'ELLEN','EMAMILTD','EMAMIPAP','EMAMIREAL','EMBDL','EMCURE','EMIL','EMKAY','EMMBI','EMSLIMITED','EMUDHRA','EMULTIMQ','ENDURANCE','ENERGYDEV','ENGINERSIN','ENIL','ENRIN','ENTERO','EPACK',
'EPIGRAL','EPL','EQUAL200','EQUAL50','EQUAL50ADD','EQUIPPP','EQUITASBNK','ERIS','ESABINDIA','ESAFSFB','ESCORTS','ESG','ESILVER','ESSARSHPNG','ESSENTIA','ESTER','ETERNAL','ETHOSLTD',
'EUREKAFORB','EUROBOND','EUROTEXIND','EVEREADY','EVERESTIND','EVIETF','EVINDIA','EXCEL','EXCELINDUS','EXICOM','EXIDEIND','EXPLEOSOL','EXXARO','FACT','FAIRCHEMOR','FAZE3Q','FCL','FCSSOFT',
'FDC','FEDERALBNK','FEDFINA','FIBERWEB','FIEMIND','FILATEX','FILATFASH','FINCABLES','FINEORG','FINIETF','FINOPB','FINPIPE','FIRSTCRY','FISCHER','FIVESTAR','FLAIR','FLEXITUFF','FLUOROCHEM',
'FMCGIETF','FMGOETZE','FMNL','FOCUS','FOODSIN','FORCEMOT','FORTIS','FOSECOIND','FSL','FUSION','GABRIEL','GAEL','GAIL','GALAPREC','GALAXYSURF','GALLANTT','GANDHAR','GANDHITUBE','GANECOS',
'GANESHBE','GANESHHOUC','GANGAFORGE','GANGESSECU','GARFIBRES','GARUDA','GATECH','GATECHDVR','GATEWAY','GAYAHWS','GEECEE','GEEKAYWIRE','GEMAROMA','GENCON','GENESYS','GENUSPAPER',
'GENUSPOWER','GEOJITFSL','GESHIP','GFLLIMITED','GHCL','GHCLTEXTIL','GICHSGFIN','GICRE','GILLANDERS','GILLETTE','GILT5YBEES','GINNIFILA','GIPCL','GKWLIMITED','GLAND','GLAXO','GLENMARK',
'GLFL','GLOBAL','GLOBALE','GLOBALVECT','GLOBE','GLOBECIVIL','GLOBUSSPR','GLOSTERLTD','GMBREW','GMDCLTD','GMMPFAUDLR','GMRAIRPORT','GMRP&UI','GNA','GNFC','GOACARBON','GOCLCORP','GOCOLORS',
'GODAVARIB','GODFRYPHLP','GODHA','GODIGIT','GODREJAGRO','GODREJCP','GODREJIND','GODREJPROP','GOKEX','GOKUL','GOKULAGRO','GOLD1','GOLD360','GOLDBEES','GOLDCASE','GOLDETF','GOLDETFADD',
'GOLDIAM','GOLDIETF','GOLDSHARE','GOLDTECH','GOODLUCK','GOPAL','GOYALALUM','GPIL','GPPL','GPTHEALTH','GPTINFRA','GRANULES','GRAPHITE','GRASIM','GRAVITA','GREAVESCOT','GREENLAM','GREENPANEL',
'GREENPLY','GREENPOWER','GRINDWELL','GRINFRA','GRMOVER','GROBTEA','GROWWDEFNC','GROWWEV','GROWWGOLD','GROWWLIQID','GROWWLOVOL','GROWWMOM50','GROWWN200','GROWWNET','GROWWNIFTY','GROWWNXT50',
'GROWWPOWER','GROWWRAIL','GROWWSLVR','GRPLTD','GRSE','GRWRHITECH','GSEC10ABSL','GSEC10IETF','GSEC10YEAR','GSEC5IETF','GSFC','GSLSU','GSPL','GSS','GTL','GTLINFRA','GTPL','GUFICBIO','GUJALKALI',
'GUJAPOLLO','GUJGASLTD','GUJRAFFIA','GUJTHEM','GULFOILLUB','GULFPETRO','GULPOLY','GVKPIL','GVPIL','GVPTECH','GVT&D','HAL','HAPPSTMNDS','HAPPYFORGE','HARDWYN','HARIOMPIPE','HARRMALAYA','HARSHA',
'HATHWAY','HATSUN','HAVELLS','HAVISHA','HBLENGINE','HBSL','HCC','HCG','HCL_INSYS','HCLTECH','HDBFS','HDFCAMC','HDFCBANK','HDFCBSE500','HDFCGOLD','HDFCGROWTH','HDFCLIFE','HDFCLIQUID',
'HDFCLOWVOL','HDFCMID150','HDFCMOMENT','HDFCNEXT50','HDFCNIF100','HDFCNIFBAN','HDFCNIFIT','HDFCNIFTY','HDFCPSUBK','HDFCPVTBAN','HDFCQUAL','HDFCSENSEX','HDFCSILVER','HDFCSML250','HDFCVALUE',
'HEADSUP','HEALTHADD','HEALTHIETF','HEALTHY','HECPROJECT','HEG','HEIDELBERG','HEMIPROP','HERANBA','HERCULES','HERITGFOOD','HEROMOTOCO','HESTERBIO','HEUBACHIND','HEXATRADEX','HEXT','HFCL',
'HGINFRA','HGS','HIKAL','HILINFRA','HILTON','HIMATSEIDE','HINDALCO','HINDCOMPOS','HINDCON','HINDCOPPER','HINDMOTORS','HINDNATGLS','HINDOILEXP','HINDPETRO','HINDUNILVR','HINDWAREAP','HINDZINC',
'HIRECT','HISARMETAL','HITECH','HITECHCORP','HITECHGEAR','HLEGLAS','HLVLTD','HMAAGRO','HMVL','HNDFDS','HNGSNGBEES','HOMEFIRST','HONASA','HONAUT','HONDAPOWER','HOVS','HPAL','HPIL','HPL','HSCL',
'HTMEDIA','HUBTOWN','HUDCO','HUHTAMAKI','HYBRIDFIN','HYUNDAI','ICDSLTD','ICEMAKE','ICICIB22','ICICIBANK','ICICIGI','ICICIPRULI','ICIL','ICRA','IDBI','IDEA','IDEAFORGE','IDFCFIRSTB','IDFNIFTYET',
'IEL','IEX','IFBAGRO','IFBIND','IFCI','IFGLEXPOR','IGARASHI','IGCL','IGIL','IGL','IGPL','IIFL','IIFLCAPS','IITL','IKIO','IKS','IMAGICAA','IMFA','IMPAL','INCREDIBLE','INDBANK','INDGN','INDHOTEL',
'INDIACEM','INDIAGLYCO','INDIAMART','INDIANB','INDIANCARD','INDIANHUME','INDIASHLTR','INDIGO','INDIGOPNTS','INDIQUBE','INDNIPPON','INDOAMIN','INDOBORAX','INDOCO','INDOFARM','INDORAMA','INDOSTAR',
'INDOTECH','INDOTHAI','INDOUS','INDOWIND','INDRAMEDCO','INDSWFTLAB','INDTERRAIN','INDUSINDBK','INDUSTOWER','INFIBEAM','INFOBEAN','INFRABEES','INFRAIETF','INFY','INGERRAND','INNOVACAP','INNOVANA',
'INOXGREEN','INOXINDIA','INOXWIND','INSECTICID','INSPIRISYS','INTELLECT','INTENTECH','INTERARCH','INTERNET','INTLCONV','INVENTURE','IOB','IOC','IOLCP','IONEXCHANG','IPCALAB','IPL','IRB','IRCON',
'IRCTC','IREDA','IRFC','IRIS','IRISDOREME','IRMENERGY','ISFT','ISGEC','ISHANCH','IT','ITBEES','ITC','ITCHOTELS','ITDC','ITDCEM','ITETF','ITETFADD','ITI','ITIETF','IVC','IVP','IVZINGOLD',
'IVZINNIFTY','IXIGO','IZMO','J&KBANK','JAGRAN','JAGSNPHARM','JAIBALAJI','JAICORPLTD','JAIPURKURT','JAMNAAUTO','JASH','JAYAGROGN','JAYBARMARU','JAYNECOIND','JAYSREETEA','JBCHEPHARM','JBMA',
'JCHAC','JETFREIGHT','JGCHEM','JHS','JINDALPHOT','JINDALPOLY','JINDALSAW','JINDALSTEL','JINDRILL','JINDWORLD','JIOFIN','JISLDVREQS','JISLJALEQS','JITFINFRA','JKCEMENT','JKIL','JKLAKSHMI',
'JKPAPER','JKTYRE','JLHL','JMA','JMFINANCIL','JNKINDIA','JOCIL','JPOLYINVST','JPPOWER','JSFB','JSL','JSLL','JSWCEMENT','JSWENERGY','JSWHL','JSWINFRA','JSWSTEEL','JTEKTINDIA','JTLIND','JUBLCPL',
'JUBLFOOD','JUBLINGREA','JUBLPHARMA','JUNIORBEES','JUNIPER','JUSTDIAL','JWL','JYOTHYLAB','JYOTICNC','JYOTISTRUC','KABRAEXTRU','KAJARIACER','KAKATCEM','KALAMANDIR','KALPATARU','KALYANIFRG',
'KALYANKJIL','KAMATHOTEL','KAMDHENU','KAMOPAINTS','KANANIIND','KANORICHEM','KANPRPLA','KANSAINER','KAPSTON','KARMAENG','KARURVYSYA','KAUSHALYA','KAVDEFENCE','KAYA','KAYNES','KCP','KCPSUGIND',
'KDDL','KEC','KECL','KEEPLEARN','KEI','KELLTONTEC','KERNEX','KESORAMIND','KEYFINSERV','KFINTECH','KHADIM','KHAICHEM','KHAITANLTD','KHANDSE','KICL','KILITCH','KIMS','KINGFA','KIOCL','KIRIINDUS',
'KIRLOSBROS','KIRLOSENG','KIRLOSIND','KIRLPNU','KITEX','KKCL','KMEW','KMSUGAR','KNRCON','KOHINOOR','KOKUYOCMLN','KOLTEPATIL','KOPRAN','KOTAKBANK','KOTARISUG','KOTHARIPET','KOTHARIPRO','KPEL',
'KPIGREEN','KPIL','KPITTECH','KPRMILL','KRBL','KREBSBIO','KRIDHANINF','KRISHANA','KRISHIVAL','KRITI','KRITIKA','KRITINUT','KRN','KRONOX','KROSS','KRSNAA','KRYSTAL','KSB','KSCL','KSHITIJPOL',
'KSL','KSOLVES','KTKBANK','KUANTUM','LAGNAM','LAL','LALPATHLAB','LAMBODHARA','LANCORHOL','LANDMARK','LAOPALA','LASA','LATENTVIEW','LATTEYS','LAURUSLABS','LAXMICOT','LAXMIDENTL','LAXMIINDIA',
'LCCINFOTEC','LEMONTREE','LEXUS','LFIC','LGBBROSLTD','LGHL','LIBAS','LIBERTSHOE','LICHSGFIN','LICI','LICMFGOLD','LICNETFGSC','LICNETFN50','LICNETFSEN','LICNFNHGP','LICNMID100','LIKHITHA',
'LINC','LINCOLN','LINDEINDIA','LIQGRWBEES','LIQUID','LIQUID1','LIQUIDADD','LIQUIDBEES','LIQUIDBETF','LIQUIDCASE','LIQUIDETF','LIQUIDIETF','LIQUIDPLUS','LIQUIDSBI','LIQUIDSHRI','LLOYDSENGG',
'LLOYDSENT','LLOYDSE_RE','LLOYDSME','LMW','LODHA','LOKESHMACH','LORDSCHLO','LOTUSDEV','LOTUSEYE','LOVABLE','LOWVOL','LOWVOL1','LOWVOLIETF','LOYALTEX','LPDC','LT','LTF','LTFOODS','LTGILTBEES',
'LTGILTCASE','LTIM','LTTS','LUMAXIND','LUMAXTECH','LUPIN','LUXIND','LXCHEM','LYKALABS','LYPSAGEMS','M&M','M&MFIN','MAANALU','MACPOWER','MADHAV','MADHUCON','MADRASFERT','MAFANG','MAGADSUGAR',
'MAGNUM','MAHABANK','MAHAPEXLTD','MAHASTEEL','MAHEPC','MAHESHWARI','MAHKTECH','MAHLIFE','MAHLOG','MAHSCOOTER','MAHSEAMLES','MAITHANALL','MAKEINDIA','MALLCOM','MALUPAPER','MAMATA','MANAKALUCO',
'MANAKCOAT','MANAKSIA','MANAKSTEEL','MANALIPETC','MANAPPURAM','MANBA','MANCREDIT','MANGALAM','MANGCHEFER','MANGLMCEM','MANINDS','MANINFRA','MANKIND','MANOMAY','MANORAMA','MANORG','MANUFGBEES',
'MANUGRAPH','MANYAVAR','MAPMYINDIA','MARALOVER','MARATHON','MARICO','MARINE','MARKSANS','MARUTI','MASFIN','MASPTOP50','MASTEK','MASTERTR','MATRIMONY','MAWANASUG','MAXESTATES','MAXHEALTH','MAXIND',
'MAYURUNIQ','MAZDA','MAZDOCK','MBAPL','MBEL','MBLINFRA','MCL','MCLEODRUSS','MCLOUD','MCX','MEDANTA','MEDIASSIST','MEDICAMEQ','MEDICO','MEDPLUS','MEGASOFT','MEGASTAR','MEIL','MENONBE','METAL',
'METALIETF','METROBRAND','METROPOLIS','MFML','MFSL','MGEL','MGL','MHLXMIRU','MHRIL','MICEL','MID150','MID150BEES','MID150CASE','MIDCAP','MIDCAPETF','MIDCAPIETF','MIDHANI','MIDQ50ADD','MIDSELIETF',
'MIDSMALL','MINDACORP','MINDTECK','MIRCELECTR','MIRZAINT','MITCON','MITTAL','MKPL','MMFL','MMP','MMTC','MNC','MOALPHA50','MOBIKWIK','MOCAPITAL','MODEFENCE','MODIRUBBER','MODISONLTD','MODTHREAD',
'MOGOLD','MOGSEC','MOHEALTH','MOHITIND','MOIL','MOINFRA','MOKSH','MOL','MOLDTECH','MOLDTKPAC','MOLOWVOL','MOM100','MOM30IETF','MOM50','MOMENTUM','MOMENTUM50','MOMGF','MOMIDMTM','MOMOMENTUM',
'MON100','MON50EQUAL','MONARCH','MONEXT50','MONIFTY500','MONQ50','MONTECARLO','MOPSE','MOQUALITY','MOREALTY','MOREPENLAB','MOSCHIP','MOSILVER','MOSMALL250','MOTHERSON','MOTILALOFS','MOTISONS',
'MOTOGENFIN','MOTOUR','MOVALUE','MPHASIS','MPSLTD','MRF','MRPL','MSCIINDIA','MSPL','MSTCLTD','MSUMI','MTARTECH','MTEDUCARE','MTNL','MUFIN','MUFTI','MUKANDLTD','MUKKA','MUKTAARTS','MULTICAP',
'MUNJALAU','MUNJALSHOW','MURUDCERA','MUTHOOTCAP','MUTHOOTFIN','MUTHOOTMF','MVGJL','NACLIND','NAGAFERT','NAGREEKCAP','NAGREEKEXP','NAHARCAP','NAHARINDUS','NAHARPOLY','NAHARSPING','NAM_INDIA',
'NARMADA','NATCAPSUQ','NATCOPHARM','NATHBIOGEN','NATIONALUM','NAUKRI','NAVA','NAVINFLUOR','NAVKARCORP','NAVKARURB','NAVNETEDUL','NAZARA','NBCC','NBIFIN','NCC','NCLIND','NDGL','NDL','NDLVENTURE',
'NDRAUTO','NDTV','NECCLTD','NECLIFE','NELCAST','NELCO','NEOGEN','NESCO','NESTLEIND','NETF','NETWEB','NETWORK18','NEULANDLAB','NEWGEN','NEXT30ADD','NEXT50','NEXT50IETF','NEXTMEDIA','NFL','NGIL',
'NGLFINE','NH','NHPC','NIACL','NIBE','NIBL','NIF100BEES','NIF100IETF','NIF10GETF','NIF5GETF','NIFITETF','NIFMID150','NIFTY1','NIFTY100EW','NIFTY50ADD','NIFTYBEES','NIFTYBETF','NIFTYETF','NIFTYIETF',
'NIFTYQLITY','NIITLTD','NIITMTS','NILAINFRA','NILASPACES','NILKAMAL','NINSYS','NIPPOBATRY','NIRAJ','NIRAJISPAT','NITCO','NITINSPIN','NITIRAJ','NIVABUPA','NKIND','NLCINDIA','NMDC','NOCIL','NOIDATOLL',
'NORBTEAEXP','NORTHARC','NOVAAGRI','NPBET','NPST','NRAIL','NRBBEARING','NRL','NSIL','NSLNISP','NTPC','NTPCGREEN','NUCLEUS','NURECA','NUVAMA','NUVOCO','NV20','NV20BEES','NV20IETF','NYKAA','OAL','OBCL',
'OBEROIRLTY','OCCLLTD','ODIGMA','OFSS','OIL','OILCOUNTUB','OILIETF','OLAELEC','OLECTRA','OMAXAUTO','OMAXE','OMINFRAL','ONELIFECAP','ONEPOINT','ONESOURCE','ONGC','ONMOBILE','ONWARDTEC','OPTIEMUS','ORBTEXP',
'ORCHASP','ORCHPHARMA','ORICONENT','ORIENTALTL','ORIENTBELL','ORIENTCEM','ORIENTCER','ORIENTELEC','ORIENTHOT','ORIENTLTD','ORIENTPPR','ORIENTTECH','ORISSAMINE','ORTINGLOBE','OSIAHYPER','OSWALAGRO',
'OSWALGREEN','OSWALPUMPS','OSWALSEEDS','PAGEIND','PAISALO','PAKKA','PALASHSECU','PANACEABIO','PANACHE','PANAMAPET','PANSARI','PAR','PARACABLES','PARADEEP','PARAGMILK','PARAS','PARASPETRO','PARKHOTELS',
'PARSVNATH','PASHUPATI','PASUPTAC','PATANJALI','PATELENG','PATELRMART','PATINTLOG','PAVNAIND','PAYTM','PCBL','PCJEWELLER','PDMJEPAPER','PDSL','PEARLPOLY','PEL','PENIND','PENINLAND','PERSISTENT','PETRONET',
'PFC','PFIZER','PFOCUS','PFS','PGEL','PGHH','PGHL','PGIL','PHARMABEES','PHOENIXLTD','PICCADIL','PIDILITIND','PIGL','PIIND','PILANIINVS','PILITA','PIONEEREMB','PITTIENG','PIXTRANS','PKTEA','PLASTIBLEN',
'PLATIND','PLAZACABLE','PNB','PNBGILTS','PNBHOUSING','PNC','PNCINFRA','PNGJL','POCL','PODDARMENT','POKARNA','POLICYBZR','POLYCAB','POLYMED','POLYPLEX','PONNIERODE','POONAWALLA','POWERGRID','POWERINDIA',
'POWERMECH','PPAP','PPL','PPLPHARMA','PRABHA','PRAENG','PRAJIND','PRAKASH','PRAKASHSTL','PRAXIS','PRECAM','PRECOT','PRECWIRE','PREMEXPLN','PREMIER','PREMIERENE','PREMIERPOL','PRESTIGE','PRICOLLTD',
'PRIMESECU','PRIMO','PRINCEPIPE','PRITI','PRITIKAUTO','PRIVISCL','PROSTARM','PROTEAN','PROZONER','PRSMJOHNSN','PRUDENT','PRUDMOULI','PSB','PSPPROJECT','PSUBANK','PSUBANKADD','PSUBNKBEES','PSUBNKIETF',
'PTC','PTCIL','PTL','PUNJABCHEM','PURVA','PVP','PVRINOX','PVSL','PVTBANIETF','PVTBANKADD','PYRAMID','QGOLDHALF','QNIFTY','QPOWER','QUADFUTURE','QUAL30IETF','QUALITY30','QUESS','QUICKHEAL','RACE',
'RACLGEAR','RADAAN','RADHIKAJWE','RADIANTCMS','RADICO','RADIOCITY','RAILTEL','RAIN','RAINBOW','RAJESHEXPO','RAJMET','RAJOOENG','RAJRATAN','RAJRILTD','RAJSREESUG','RAJTV','RALLIS','RAMANEWS','RAMAPHO',
'RAMASTEEL','RAMCOCEM','RAMCOIND','RAMCOSYS','RAMKY','RAMRAT','RANASUG','RANEHOLDIN','RATEGAIN','RATNAMANI','RATNAVEER','RAYMOND','RAYMONDLSL','RAYMONDREL','RBA','RBLBANK','RBZJEWEL','RCF','RCOM','RECLTD',
'REDINGTON','REDTAPE','REFEX','REGAAL','REGENCERAM','RELAXO','RELCHEMQ','RELIABLE','RELIANCE','RELIGARE','RELINFRA','RELTD','REMSONSIND','RENUKA','REPCOHOME','REPL','REPRO','RESPONIND','RETAIL','RGL',
'RHFL','RHIM','RHL','RICOAUTO','RIIL','RISHABH','RITCO','RITES','RKDL','RKEC','RKFORGE','RKSWAMY','RMDRIP','RML','ROHLTD','ROLEXRINGS','ROLLT','ROML','ROSSARI','ROSSELLIND','ROSSTECH','ROTO','ROUTE','RPEL',
'RPGLIFE','RPOWER','RPPINFRA','RPPL','RPSGVENT','RPTECH','RRKABEL','RSSOFTWARE','RSWM','RSYSTEMS','RTNINDIA','RTNPOWER','RUBFILA','RUBYMILLS','RUCHINFRA','RUCHIRA','RUPA','RUSHIL','RUSTOMJEE','RVHL',
'RVNL','RVTH','S&SPOWER','SABEVENTS','SABTNL','SADBHAV','SADBHIN','SADHNANIQ','SAFARI','SAGARDEEP','SAGCEM','SAGILITY','SAHYADRI','SAIL','SAILIFE','SAKAR','SAKHTISUG','SAKSOFT','SAKUMA','SALASAR','SALONA',
'SALSTEEL','SALZERELEC','SAMBHAAV','SAMBHV','SAMHI','SAMMAANCAP','SAMPANN','SANATHAN','SANDESH','SANDHAR','SANDUMA','SANGAMIND','SANGHIIND','SANGHVIMOV','SANGINITA','SANOFI','SANOFICONR','SANSERA','SANSTAR',
'SAPPHIRE','SARDAEN','SAREGAMA','SARLAPOLY','SARVESHWAR','SASKEN','SASTASUNDR','SATIA','SATIN','SAURASHCEM','SBC','SBCL','SBFC','SBGLP','SBIBPB','SBICARD','SBIETFCON','SBIETFIT','SBIETFPB','SBIETFQLTY',
'SBILIFE','SBIN','SBINEQWETF','SBISILVER','SCHAEFFLER','SCHAND','SCHNEIDER','SCI','SCILAL','SCODATUBES','SCPL','SDBL','SDL26BEES','SEAMECLTD','SECMARK','SECURKLOUD','SEJALLTD','SELAN','SELECTIPO','SELMC',
'SEMAC','SENCO','SENORES','SENSEXADD','SENSEXETF','SENSEXIETF','SEPC','SEQUENT','SERVOTECH','SESHAPAPER','SETCO','SETF10GILT','SETFGOLD','SETFNIF50','SETFNIFBK','SETFNN50','SEYAIND','SFL','SGFIN','SGIL',
'SGL','SGLTL','SHAH','SHAHALLOYS','SHAILY','SHAKTIPUMP','SHALBY','SHALPAINTS','SHANKARA','SHANTI','SHANTIGEAR','SHANTIGOLD','SHARDACROP','SHARDAMOTR','SHAREINDIA','SHARIABEES','SHEKHAWATI','SHEMAROO',
'SHILPAMED','SHIVALIK','SHIVAMAUTO','SHIVAMILLS','SHIVATEX','SHK','SHOPERSTOP','SHRADHA','SHREDIGCEM','SHREECEM','SHREEJISPG','SHREEPUSHK','SHREERAMA','SHRENIK','SHREYANIND','SHRIPISTON','SHRIRAMFIN',
'SHRIRAMPPS','SHYAMCENT','SHYAMMETL','SHYAMTEL','SICALLOG','SIEMENS','SIGACHI','SIGIND','SIGMA','SIGNATURE','SIGNPOST','SIKKO','SIL','SILGO','SILINV','SILLYMONKS','SILVER','SILVER1','SILVER360',
'SILVERADD','SILVERBEES','SILVERCASE','SILVERETF','SILVERIETF','SILVERTUC','SILVRETF','SIMBHALS','SIMPLEXINF','SINCLAIR','SINDHUTRAD','SINTERCOM','SIRCA','SIS','SIYSIL','SJS','SJVN','SKFINDIA',
'SKIPPER','SKMEGGPROD','SKYGOLD','SMALLCAP','SMARTLINK','SMARTWORKS','SMCGLOBAL','SMLISUZU','SMLT','SMSLIFE','SMSPHARMA','SNOWMAN','SNXT30BEES','SOBHA','SOFTTECH','SOLARA','SOLARINDS','SOMANYCERA',
'SOMATEX','SOMICONVEY','SONACOMS','SONAMLTD','SONATSOFTW','SOTL','SOUTHBANK','SOUTHWEST','SPAL','SPANDANA','SPARC','SPCENET','SPECIALITY','SPECTRUM','SPENCERS','SPIC','SPLIL','SPLPETRO','SPMLINFRA',
'SPORTKING','SRD','SREEL','SRF','SRGHFL','SRHHYPOLTD','SRM','SSDL','SSWL','STALLION','STANLEY','STAR','STARCEMENT','STARHEALTH','STARPAPER','STARTECK','STCINDIA','STEELCAS','STEELCITY','STEELXIND',
'STEL','STERTOOLS','STLTECH','STOVEKRAFT','STYLAMIND','STYLEBAAZA','STYRENIX','SUBEXLTD','SUBROS','SUDARSCHEM','SUKHJITS','SULA','SUMEETINDS','SUMICHEM','SUMIT','SUMMITSEC','SUNCLAY','SUNDARAM',
'SUNDARMFIN','SUNDARMHLD','SUNDRMBRAK','SUNDRMFAST','SUNDROP','SUNFLAG','SUNPHARMA','SUNTECK','SUNTV','SUPERHOUSE','SUPERSPIN','SUPRAJIT','SUPREME','SUPREMEIND','SUPRIYA','SURAJEST','SURAJLTD',
'SURAKSHA','SURANASOL','SURANAT&P','SURYALAXMI','SURYAROSNI','SURYODAY','SUTLEJTEX','SUVEN','SUVIDHAA','SUYOG','SUZLON','SVLL','SVPGLOB','SWANENERGY','SWARAJENG','SWELECTES','SWIGGY','SWSOLAR',
'SYMPHONY','SYNCOMF','SYNGENE','SYRMA','TAINWALCHM','TAJGVK','TAKE','TALBROAUTO','TANLA','TARACHAND','TARAPUR','TARC','TARIL','TARMAT','TARSONS','TASTYBITE','TATACHEM','TATACOMM','TATACONSUM',
'TATAELXSI','TATAGOLD','TATAINVEST','TATAMOTORS','TATAPOWER','TATASTEEL','TATATECH','TATSILV','TATVA','TBOTEK','TBZ','TCI','TCIEXP','TCIFINANCE','TCPLPACK','TCS','TDPOWERSYS','TEAMGTY','TEAMLEASE',
'TECH','TECHM','TECHNOE','TECILCHEM','TEGA','TEJASNET','TEMBO','TERASOFT','TEXINFRA','TEXMOPIPES','TEXRAIL','TFCILTD','TFL','TGBHOTELS','THANGAMAYL','THEINVEST','THEJO','THELEELA','THEMISMED',
'THERMAX','THOMASCOOK','THOMASCOTT','THYROCARE','TI','TICL','TIIL','TIINDIA','TIJARIA','TIL','TIMETECHNO','TIMKEN','TINNARUBR','TIPSFILMS','TIPSMUSIC','TIRUMALCHM','TIRUPATIFL','TITAGARH','TITAN',
'TMB','TNIDETF','TNPETRO','TNPL','TNTELE','TOKYOPLAST','TOLINS','TOP100CASE','TOP10ADD','TOP15IETF','TORNTPHARM','TORNTPOWER','TOTAL','TOUCHWOOD','TPHQ','TPLPLASTEH','TRACXN','TRANSRAILL','TRANSWORLD',
'TRAVELFOOD','TREEHOUSE','TREJHARA','TREL','TRENT','TRF','TRIDENT','TRIGYN','TRITURBINE','TRIVENI','TRU','TTKHLTCARE','TTKPRESTIG','TTL','TTML','TVSELECT','TVSHLTD','TVSMOTOR','TVSSCS','TVSSRICHAK',
'TVTODAY','TVVISION','UBL','UCAL','UCOBANK','UDS','UFLEX','UFO','UGARSUGAR','UGROCAP','UJJIVANSFB','ULTRACEMCO','UMAEXPORTS','UMESLTD','UMIYA_MRO','UNICHEMLAB','UNIDT','UNIECOM','UNIENTER','UNIINFO',
'UNIMECH','UNIONBANK','UNIONGOLD','UNIPARTS','UNITDSPR','UNITEDPOLY','UNITEDTEA','UNIVASTU','UNIVCABLES','UNIVPHOTO','UNOMINDA','UPL','URAVIDEF','URJA','USHAMART','USK','UTIAMC','UTISXN50','UTKARSHBNK',
'UTTAMSUGAR','UYFINCORP','V2RETAIL','VADILALIND','VAIBHAVGBL','VAISHALI','VAKRANGEE','VAL30IETF','VALIANTLAB','VALIANTORG','VARDHACRLC','VARDMNPOLY','VARROC','VASCONEQ','VASWANI','VBL','VCL','VEDL',
'VEEDOL','VENKEYS','VENTIVE','VENUSPIPES','VENUSREM','VERANDA','VERTOZ','VESUVIUS','VETO','VGUARD','VHL','VHLTD','VIDHIING','VIJAYA','VIJIFIN','VIKASECO','VIKASLIFE','VIKRAMSOLR','VIMTALABS','VINATIORGA',
'VINCOFE','VINDHYATEL','VINEETLAB','VINNY','VINYLINDIA','VIPCLOTHNG','VIPIND','VIPULLTD','VIRINCHI','VISAKAIND','VISASTEEL','VISHNU','VISHWARAJ','VIVIDHA','VLEGOV','VLSFINANCE','VMART','VMM','VOLTAMP',
'VOLTAS','VPRPL','VRAJ','VRLLOG','VSSL','VSTIND','VSTL','VSTTILLERS','VTL','WAAREEENER','WAAREERTL','WABAG','WALCHANNAG','WANBURY','WCIL','WEALTH','WEBELSOLAR','WEIZMANIND','WEL','WELCORP','WELENT',
'WELINV','WELSPUNLIV','WENDT','WESTLIFE','WEWIN','WHEELS','WHIRLPOOL','WILLAMAGOR','WINDLAS','WINDMACHIN','WIPL','WIPRO','WOCKPHARMA','WONDERLA','WORTH','WSI','WSTCSTPAPR','XCHANGING','XELPMOC',
'XPROINDIA','XTGLOBAL','YAARI','YASHO','YATHARTH','YATRA','YESBANK','YUKEN','ZAGGLE','ZEEL','ZEELEARN','ZEEMEDIA','ZENITHEXPO','ZENITHSTL','ZENSARTECH','ZENTEC','ZFCVINDIA','ZIMLAB','ZODIAC',
'ZODIACLOTH','ZOTA','ZUARI','ZUARIIND','ZYDUSLIFE','ZYDUSWELL']

# ============================================================
# SAFE NSE SESSION (CREATED ONLY WHEN CALLED)
# ============================================================
def nse_session():
    s = requests.Session()
    s.headers.update({
        "User-Agent": "Mozilla/5.0",
        "Accept": "application/json",
        "Referer": "https://www.nseindia.com/"
    })
    return s

# ============================================================
# FETCH NSE ORDERS (ON-DEMAND ONLY)
# ============================================================
def fetch_nse_orders():
    s = nse_session()
    s.get("https://www.nseindia.com", timeout=5)

    url = "https://www.nseindia.com/api/corporate-announcements?index=equities"
    r = s.get(url, timeout=5)

    df = pd.DataFrame(r.json())

    df = df[df["desc"].str.contains(
        "order|contract|award|project|loa",
        case=False,
        na=False
    )]

    df["Date"] = pd.to_datetime(df["an_dt"]).dt.date
    return df[["symbol", "desc", "Date"]]

# ============================================================
# FETCH NSE EQUITY (ON-DEMAND ONLY)
# ============================================================
def fetch_nse_equity(symbol):
    s = nse_session()
    s.get("https://www.nseindia.com", timeout=5)

    url = f"https://www.nseindia.com/api/quote-equity?symbol={symbol}"
    r = s.get(url, timeout=5)
    data = r.json()

    price = data["priceInfo"]
    meta = data["metadata"]

    return {
        "symbol": symbol,
        "marketCap": meta.get("marketCap"),
        "volume": price.get("totalTradedVolume"),
        "sector": meta.get("industry", "NA")
    }

# ============================================================
# EXTRACT ORDER VALUE
# ============================================================
def extract_order_value(text):
    m = re.search(r"(₹|Rs\.?)\s?([\d,]+)\s?crore", text, re.I)
    return float(m.group(2).replace(",", "")) if m else None

# ============================================================
# UI – NOTHING BLOCKING ABOVE THIS LINE
# ============================================================

st.info("⚠ NSE APIs are called **only after clicking the button**")

if st.button("🚀 Fetch NSE Orders & Rank Impact"):
    with st.spinner("Fetching data from NSE…"):

        try:
            orders = fetch_nse_orders()
            st.subheader("🔁 NSE Order Announcements")
            st.dataframe(orders, use_container_width=True)

            results = []

            for sym in SYMBOLS:
                eq = fetch_nse_equity(sym)
                if not eq or not eq["marketCap"]:
                    continue

                for _, r in orders[orders.symbol == sym].iterrows():
                    order_val = extract_order_value(r.desc)
                    if not order_val:
                        continue

                    impact = min((order_val / (eq["marketCap"] / 1e7)) * 5, 100)

                    results.append({
                        "Stock": sym,
                        "Order ₹Cr": order_val,
                        "Market Cap ₹Cr": round(eq["marketCap"] / 1e7, 0),
                        "Order % MCap": round((order_val / (eq["marketCap"] / 1e7)) * 100, 2),
                        "Sector": eq["sector"],
                        "Impact Score": round(impact, 1)
                    })

            if results:
                df = pd.DataFrame(results).sort_values(
                    "Impact Score", ascending=False
                )

                st.subheader("🧠 Order Impact Ranking")
                st.dataframe(df, use_container_width=True)
            else:
                st.warning("No matching NSE orders for predefined symbols.")

        except Exception as e:
            st.error("NSE blocked the request. Please retry later.")
            st.code(str(e))

# ============================================================
# FOOTER
# ============================================================
st.markdown("---")
st.markdown("""
**Designed by – Gaurav Singh Yadav**  
📦 NSE Order Flow | 🧠 Institutional Tracking  
""")
